"Device detail info"
type Device {
  "Device id"
  id: ID
  "Current device status"
  deviceStatus: DeviceStatus
  "Current app status"
  appStatus: AppStatus
  "Device network params"
  deviceNetwork: DeviceNetwork
  "Message timestamp"
  timestamp: BigInt
}

"Current device status"
type DeviceStatus {
  "Device serial"
  devSn: String
  "Display serial"
  displaySn: String
  "Device type"
  type: String
  "Connector Serial"
  connectorSn: String
  "Device name"
  hostname: String
  "information of device memory"
  deviceDataList: [DeviceData]
  "Information of device voltage"
  voltage: Voltage
  "Device uptime"
  upTime: String
  "Device temperature"
  temperature: Int
  "CPU status"
  cpuStatus: [Float]
  "Device iot connected"
  online: Boolean
  "Device Ram status"
  ram: DeviceData
  "Group name where is integrated the device"
  groupName: String
}

"Current app status"
type AppStatus {
  "Civica tables version"
  appTablesVersion: AppTablesVersion
  "Current tables availables in device"
  appVersions: [AppVersionDescription]
  "App time stamp"
  timestamp: BigInt
}

"Device network params"
type DeviceNetwork {
  "Modem serial"
  modemSn: String
  "Gatway"
  gateway: String
  "Wifi serial"
  wifiSn: String
  "Mac address"
  mac: String
  "DNS address"
  dns: String
  "Curent SIM status"
  simStatus: String
  "SIM IMEI"
  simImei: String
  "Information of interfaces in a device"
  ipMaskMap: [Interface]
  "Modem band"
  band: String
  "Modem mode"
  mode: String
}

"Information of interfaces in a device"
type Interface {
  "Interface name"
  name: String
  "Interface addresses"
  addresses: [String]
}

"Current tables availables in device"
type AppVersionDescription {
  "Table name"
  name: String
  "Table version"
  version: String
}

"Civica tables version"
type AppTablesVersion {
  "Table fare policy"
  farePolicy: String
  "Table black list"
  blackList: String
}

"information of RAM, FLASH and SD"
type DeviceData {
  "Memory total value"
  totalValue: Float
  "Memory current value"
  currentValue: Float
  "Memory unit information (Mib, Kib)"
  memoryUnitInformation: MemoryUnitInformation
  "Memory type"
  memorytype: MemoryType
}

"Memory type in Device"
enum MemoryType {
  "Device RAM memory"
  RAM
  "Device FLASH memory"
  FLASH
  "Device SD memory"
  SD
}

enum MemoryUnitInformation {
  "Byte"
  B
  "Kibibyte"
  KiB
  "Mebibite"
  MiB
  "Gibibyte"
  GiB
}

"Information of voltage state"
type Voltage {
  "Current device voltage value"
  currentValue: Float
  "Highest device voltage value"
  highestValue: Float
  "Lowest device voltage value"
  lowestValue: Float
}

type VoltageAvgInRangeOfTime {
  currentValue: Float
  lowestValue: Float
  highestValue: Float
  interval: BigInt
}

type VolumeInRageOfTime {
  value: Float
  timestamp: BigInt
}
type CpuInRageOfTime {
  value: Float
  timestamp: BigInt
}

type Query {
  "Get device detail filtered by the device id"
  getDeviceDetail(id: ID!): Device

  "Get all devices"
  getDevices(page: Int!, count: Int!, filter: String, sortColumn: String, sortOrder: String): [Device]

  "Get the size of table Device"
  getDeviceTableSize: Int

  getRamAvgInRangeOfTime(
    initTime: BigInt
    endTime: BigInt
    deviceId: String
  ): [Device]

  getVolumeAvgInRangeOfTime(
    initTime: BigInt
    endTime: BigInt
    volumeType: String
    deviceId: String
  ): [VolumeInRageOfTime]

  getCpuAvgInRangeOfTime(
    initTime: BigInt
    endTime: BigInt
    deltaTime: Int
    deviceId: String
  ): [CpuInRageOfTime]

  getVoltageInRangeOfTime(
    initTime: BigInt
    endTime: BigInt
    deviceId: String
  ): [Device]
}

type Subscription {
  DeviceVolumesStateReportedEvent(ids: [ID]): Device
  DeviceDisplayStateReportedEvent(id: ID): Device
  DeviceSystemStateReportedEvent(ids: [ID]): Device
  DeviceDeviceStateReportedEvent(ids: [ID]): Device
  DeviceLowestVoltageReportedEvent(id: ID): Device
  DeviceHighestVoltageReportedEvent(id: ID): Device
  DeviceNetworkStateReportedEvent(id: ID): Device
  DeviceModemStateReportedEvent(id: ID): Device
  DeviceMainAppStateReportedEvent(id: ID): Device
  DeviceConnectedEvent(ids: [ID]): Device
  DeviceDisconnectedEvent(ids: [ID]): Device
}
